# This config represents the latest values used when running the plugin-template. Any settings that
# were not present before running plugin-template have been added with their default values.

additional_plugins: []
all: false
black: false
bootstrap: false
check_commit_message: true
coverage: false
deploy_client_to_pypi: true
deploy_client_to_rubygems: true
deploy_daily_client_to_pypi: true
deploy_daily_client_to_rubygems: true
deploy_to_pypi: true
docs: false
docs_test: true
exclude_check_commit_message: false
exclude_coverage: true
exclude_deploy_client_to_pypi: false
exclude_deploy_client_to_rubygems: false
exclude_deploy_daily_client_to_pypi: false
exclude_deploy_daily_client_to_rubygems: false
exclude_deploy_to_pypi: false
exclude_docs_test: false
exclude_mariadb_test: false
exclude_test_bindings: false
plugin_app_label: docker
plugin_camel: PulpDocker
plugin_camel_short: Docker
plugin_caps: PULP_DOCKER
plugin_caps_short: DOCKER
plugin_dash: pulp-docker
plugin_dash_short: docker
plugin_name: pulp_docker
plugin_snake: pulp_docker
plugin_snake_short: docker
pulp_settings:
  token_server: $(hostname):24816/token
  token_signature_algorithm: ES256
pydocstyle: true
pypi_username: pulp
test: false
test_bindings: true
test_performance: false
travis: true
travis_notifications: None
verbose: false

